### ISSUE TITLE
Flag torsions in linear molecules

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#21]
`torsiondrive` chokes on dihedrals where one of the angles are linear. For example in `C#CC` (prop-1-yne), the methyl rotor H-C-C3-C3 has the same energy for all torsion angles. For any torsion 1234, check that angles 123 or 234 are not linear.

**Comment by SimonBoothroyd** [comment]
These checks are now handled by `openff-qcsubmit`
