### ISSUE TITLE
Atom map from substructure match flips indices for symmetrical atoms

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#27]
This is related to https://github.com/openforcefield/cmiles/pull/15

**Comment by ChayaSt** [comment]
Turns out it also flips map indices with the newer solution in https://github.com/openforcefield/cmiles/pull/15

Example:
Mapped SMILES generated with cmiles:
`'[H:7][C:1]1([C:2]([C:4]([C:5]([C:3]1([H:11])[H:12])([H:15])[C:6]([H:16])([H:17])[H:18])([H:13])[H:14])([H:9])[H:10])[H:8]'`

Generating molecule from mapped SMILES generates this mapping:
![image](https://user-images.githubusercontent.com/6598229/52918588-c44ffa80-32c6-11e9-8c24-5bddf9768667.png)

Generating molecule from canonical SMILES, then canonicalizing the order and adding map indices as +1 of atom index (the way cmiles generates the mapped SMILES) generates this mapping:

![image](https://user-images.githubusercontent.com/6598229/52918593-cf0a8f80-32c6-11e9-872b-2dc89d86ac95.png)

@j-wags, this means that the logic I implemented here https://github.com/openforcefield/cmiles/pull/15 fails for this molecule because when the molecule's atom order generated from the mapped SMILES is canonicalized, the map indices are not +1 the atom indices.

**Comment by jchodera** [comment]
This probably is likely unavoidable, which is why for fragmenter pipelines we always want to generate the molecule with the ordering we want and continue to use that ordering/mapping throughout the remainder of the pipeline.

**Comment by ChayaSt** [comment]
The problem arises from the way fragmenter was designed. 
Fragmenter generates a list of fragments with `cmiles` IDs before the fragments have geometries as seen in this planning image:
![image](https://user-images.githubusercontent.com/6598229/52955538-e2673a80-335a-11e9-83c9-be88a5d2b9e8.png)
The way to remedy this is to have `cmiles` only generate a mapped SMILES if the input molecule also has geometry. This will create the following changes in `fragmenter` and `cmiles`:
1. fragment JSON will not have mapped SMILES
2. `cmiles` will allow `OEMol` inputs (currently only isomeric explicit hydrogen SMILES or QCJSON are allowed)
3. `cmiles` will only generate mapped SMILES if the input molecule has a geometry. It will first check that the molecule with geometry is in canonical order, and if not reorder it. It can be a good idea to have a `strict` flag here to allow mapped SMILES without geometries.

**Comment by ChayaSt** [comment]
This is not a concern because the since the atoms are symmetrical - it is the same molecule.
