### ISSUE TITLE
How to handle multiple starting conformation for coupled torsions

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#29]
https://github.com/openforcefield/fragmenter/pull/28 adds the ability to start `torsiondrive` from multiple starting conformations. It does this by driving all dihedrals provided to `genereate_grid_conformers`.

There are several open questions:
1. The reason I added the grid conformer generator was because I couldn't get omega to generate conformers by driving protons but I should be able to do it. 
2. How should we handle coupled torsions? 
As seen in the [ethylene glycol example](https://github.com/choderalab/fragmenter_data/tree/torsiondrive/ethylene_glycol), the torsion profile looks very different if one or several starting conformations are used. `torsiondrive` will find the low energy path, but it's not clear that this is the profile we should use to fit current torsion functionals that do not consider torsion correlations. 
If to fit current torsion parameters we should minimize rotation around other torsions, which profile should we use if the profiles are so different with respect to other degrees of freedom?

**Comment by SimonBoothroyd** [comment]
This behaviour is now handled directly by `openff-qcsubmit`.
