### ISSUE TITLE
Cutting a release

### ISSUE THREAD

**Issue by jchodera** [openforcefield/fragmenter#37]
@ChayaSt : Are we good to go with cutting a prerelease now? Or was there more you'd like to do first?

**Comment by ChayaSt** [comment]
After I merge #38 we should be ready to cut a prerelease.

**Comment by jchodera** [comment]
I've opened a PR to build the [0.0.3 release](https://github.com/openforcefield/fragmenter/releases/tag/0.0.3) package for omnia:
https://github.com/omnia-md/conda-recipes/pull/964

**Comment by jchodera** [comment]
The conda package is now built for `fragmenter 0.0.3`:
https://anaconda.org/omnia/fragmenter/files
However, since `fragment.expand_states()` is missing, I'm not sure we can actually use it.

**Comment by jchodera** [comment]
cc: #44 
This was just moved to [`states.enumerate_states()`](https://fragmenter.readthedocs.io/en/latest/api/index.html#enumerate-states).

**Comment by jchodera** [comment]
It looks like that happened after the 0.0.3 release, so we'll need another release now.
However, tests do not pass on travis, so I'm unsure if this repo is in a usable state.

**Comment by jchodera** [comment]
Tests pass after updating the OpenEye license (#46) so I am going to cut another release for us to use.

**Comment by jchodera** [comment]
I've just cut [0.0.4](https://github.com/openforcefield/fragmenter/releases/tag/0.0.4).
