### ISSUE TITLE
Move openeye imports inside functions that need them

### ISSUE THREAD

**Issue by jchodera** [openforcefield/fragmenter#40]
By [importing `openeye` at top level](https://github.com/openforcefield/fragmenter/blob/ee3b73bc21dc2f66ccb08160ec9427ecb5362314/fragmenter/fragment.py#L3), we guarantee that the `fragmenter` package cannot be imported if the openeye toolkits are installed even if we are using components of `fragmenter` that do not require openeye. This also causes problems for testing packages built and deployed via `omnia`. 

To enable package testing and use of the non-openeye components, we can move the `import openeye` statement inside of methods that actually need it.

**Comment by ChayaSt** [comment]
Addressed via #42
