### ISSUE TITLE
Support openforcefield.topology.Molecule?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/fragmenter#50]
A bunch of functions in `cmiles` and `fragmenter` support a random/arbitrary subset of QCSchema JSON, QCSchema `dict`, SMILES, `OEMol`, and RDKit `Mol`. 

It would be very helpful to standardize support for all of these through the `openforcefield.topology.Molecule` class, which is now stable enough to use as a standard exchange format.

**Comment by ChayaSt** [comment]
Yes, I agree those functions need standardization. It is on my to do list.

**Comment by SimonBoothroyd** [comment]
Fixed by #68
