### ISSUE TITLE
Charging molecules while only returning the original coordinates returns a wonky molecule

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#55]
When charging a molecule, and then only returning the original coordinates using the default options of `chemi.get_charges`, returns a molecule with coordinates that are wonky. This does not happen when the option to return all Omega generated conformers is used `chemi.get_charges(mol, keep_confs=-1)`

This is what a 2D rendition of the wonky molecule. This may also be the reason why steroechemistry flips during fragmentation or charging fails in the next round. 
![image](https://user-images.githubusercontent.com/6598229/71909758-a1c50b00-313e-11ea-8bea-503d57531299.png)

**Comment by SimonBoothroyd** [comment]
This should not be an issue with the refactored charging code, and so should be fixed by #68
