### ISSUE TITLE
Fragmentation fails with new openeye toolkit.

### ISSUE THREAD

**Issue by jthorton** [openforcefield/fragmenter#61]
During QCSubmit testing the fragmenter tests have started to fail with the release of the new openeye toolkit. See [here](https://github.com/openforcefield/qcsubmit/runs/896528521?check_suite_focus=true#step:8:227) for the logs. I will start to look into refactoring fragmenter to use the openforcefield toolkit to avoid these problems soon.

**Comment by j-wags** [comment]
Update: I've built a new fragmenter package that pins to `openeye-toolkits<2020` to keep this from producing broken builds in the interim.

**Comment by SimonBoothroyd** [comment]
This should be closed by #68.
