### ISSUE TITLE
Wiberg Order Not Found

### ISSUE THREAD

**Issue by ewu20** [openforcefield/fragmenter#65]
Hi, 
I am having issues running the following simple script:
`from fragmenter import fragment, chemi` 

`m= chemi.smiles_to_oemol('OC1(CN(C1)C(=O)C1=C(NC2=C(F)C=C(I)C=C2)C(F)=C(F)C=C1)[C@@H]1CCCCN1')` 
`f = fragment.WBOFragmenter(m) `
`f.fragment()` 
`f.depict_fragments(fname="example.pdf")`

Here is the error I am getting: 
____________________________________________________________________________________________________________________________________
Traceback (most recent call last):

  File "/Users/emmawu/Downloads/frag_test.py", line 23, in <module>
    frag_engine.fragment()

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/fragment.py", line 874, in fragment
    self._get_rotor_wbo()

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/fragment.py", line 958, in _get_rotor_wbo
    self.rotors_wbo[bond] = b.GetData('WibergBondOrder')

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/openeye/oechem.py", line 11734, in GetData
    return _oechem.OEBase_GetData(self, *args)

ValueError: GetData: WibergBondOrder not found.
____________________________________________________________________________________________________________________________________

I get the same error when trying to run the example script. I am not entirely sure what is causing the error. Any feedback is appreciated! Thank you! 

Best, 
Emma

**Comment by j-wags** [comment]
Hm, it may be something with the breaking changes in the 2020 OpenEye
toolkit. Could you try downgrading to the 2019 OpenEye toolkit? Your script
ran for me in the old version.

conda install -c openeye openeye-toolkits=2020

If you've already downgraded and it's still breaking, could you post the
output of `conda list` so we can see what else might be happening?

**Comment by ewu20** [comment]
Thank you @j-wags ! Downgrading to the 2019 version of Openeye worked for me!
